name: rdp_todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9  
  weather: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts: 
    - family: Caveat
      fonts:
        - asset: assets/Caveat-Regular.ttf

