// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHAuQkIpQQePxFlAnaaRf9NrGEaalYJrA',
    appId: '1:860859863440:web:737df887fc61e09d7f2315',
    messagingSenderId: '860859863440',
    projectId: 'rdp-todo-list',
    authDomain: 'rdp-todo-list.firebaseapp.com',
    storageBucket: 'rdp-todo-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQk2Lh8p9vXv4ER0Lwzqm3NAzJgOTUrs',
    appId: '1:860859863440:android:6c439e5da587e8f07f2315',
    messagingSenderId: '860859863440',
    projectId: 'rdp-todo-list',
    storageBucket: 'rdp-todo-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvwRV9Y4VqK3o3d9DwfClfrcZY8QKugRE',
    appId: '1:860859863440:ios:3a0b4b8dd8754f837f2315',
    messagingSenderId: '860859863440',
    projectId: 'rdp-todo-list',
    storageBucket: 'rdp-todo-list.appspot.com',
    iosClientId: '860859863440-77fbu1b08j3eqbg22d2k0qag2kbmhd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdpTodoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvwRV9Y4VqK3o3d9DwfClfrcZY8QKugRE',
    appId: '1:860859863440:ios:3a0b4b8dd8754f837f2315',
    messagingSenderId: '860859863440',
    projectId: 'rdp-todo-list',
    storageBucket: 'rdp-todo-list.appspot.com',
    iosClientId: '860859863440-77fbu1b08j3eqbg22d2k0qag2kbmhd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdpTodoList',
  );
}
